name: Mac Build CI

on:
  repository_dispatch:
    types: mac-build
  push:
    branches: [actionsHub, master, test-ready, TOOLS-1993-mac-build]
  pull_request:
    branches: [actionsHub]
  workflow_call:
    inputs:
      submodule:
        description: The directory of the submodule, if this workflow is being called on a submodule
        required: false
        type: string
    


jobs:
  build:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - if: inputs.submodule
        run: |
          git submodule update --init --recursive -- ${{ inputs.submodule }}
          cd ${{ inputs.submodule }}
      - name: Get Python version from Pipfile
        run: echo "PYTHON_VERSION=$(grep "python_version" Pipfile | cut -d ' ' -f 3  - | tr -d '"')" >> $GITHUB_ENV
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pipenv'
      - name: Pipenv setup
        run: |
          brew install pipenv
          pipenv check
      - name: Cache asadm and asinfo
        uses: actions/cache@v3
        id: cache-asadm-asinfo
        env:
          cache-name: cache-asadm-asinfo
        with:
          path: |
            build/bin
          key: ${{ runner.os }}-build-${{ env.PYTHON_VERSION }}-${{ env.cache-name }}-${{ hashFiles('**/*.py') }}-${{ hashFiles('**/*.json') }}
      - name: Build asadm
        if: steps.cache-asadm-asinfo.outputs.cache-hit != 'true'
        run: |
          make
      - name: Sanity Test tools
        run: |
          cd build/bin
          ls
          sudo install asadm /usr/local/bin
          ./asadm -e "info" 2>&1 | grep "Not able to connect"
          ./asinfo 2>&1 | grep "Not able to connect"
          cd -
      - uses: actions/upload-artifact@v3
        with:
          name: asadm
          path: build/bin/asadm
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        with:
          name: asinfo
          path: build/bin/asinfo
          if-no-files-found: error
